variables:
    AUDIT_AWS_SNS_ALERT_LIST:
        required: false
        type: array
        default:
            - sns-topics-inventory # not_violation 
#             - sns-topics-inventory-internal # not_violation 
#             - sns-subscriptions-inventory # not_violation 
#             - sns-subscriptions-inventory-internal # not_violation 
        description: "Which rules would you like to run? Possible values are sns-topics-inventory"
